import { Database, FileCode2, GitBranch, Network } from "lucide-react";

import { Sidebar } from "@/components/navigation/sidebar";
import { TopNav } from "@/components/navigation/top-nav";
import { GlassPanel } from "@/components/ui/glass-panel";
import { RiskBadge, StatusDot } from "@/components/ui/status";

const technologies = ["TypeScript", "Python", "Next.js", "FastAPI", "PostgreSQL", "Docker"];

export default function RepositoryIntelligencePage() {
  return <div className="min-h-screen lg:flex"><Sidebar /><div className="min-w-0 flex-1"><TopNav /><main className="space-y-6 p-5 lg:p-8"><section className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent-primary">Repository intelligence</p><h1 className="mt-2 font-display text-3xl font-semibold">Evidence-backed repository model</h1><p className="mt-2 text-sm text-ink-muted">Snapshot, scan events, dependency inventory, and knowledge graph are available through the analysis API.</p></div><RiskBadge level="low" /></section><section className="grid gap-5 lg:grid-cols-3"><GlassPanel><div className="relative"><FileCode2 className="text-accent-primary" /><p className="mt-5 text-xs uppercase tracking-[0.14em] text-ink-muted">Structure</p><p className="mt-2 font-display text-3xl font-semibold">1,248 files</p><p className="mt-2 text-sm text-ink-muted">Policy-filtered scan</p></div></GlassPanel><GlassPanel><div className="relative"><Database className="text-accent-secondary" /><p className="mt-5 text-xs uppercase tracking-[0.14em] text-ink-muted">Dependencies</p><p className="mt-2 font-display text-3xl font-semibold">42 tracked</p><p className="mt-2 text-sm text-ink-muted">Manifest-backed inventory</p></div></GlassPanel><GlassPanel><div className="relative"><Network className="text-status-success" /><p className="mt-5 text-xs uppercase tracking-[0.14em] text-ink-muted">Knowledge graph</p><p className="mt-2 font-display text-3xl font-semibold">Ready</p><p className="mt-2 text-sm text-ink-muted">Typed nodes and relationships</p></div></GlassPanel></section><section className="grid gap-5 xl:grid-cols-[1fr_0.8fr]"><GlassPanel><div className="relative"><div className="flex justify-between"><h2 className="font-display text-xl font-semibold">Technology stack</h2><StatusDot status="success" label="detected" /></div><div className="mt-6 flex flex-wrap gap-2">{technologies.map((technology) => <span key={technology} className="rounded-full border border-surface-muted bg-elevated px-3 py-1.5 text-sm text-ink-muted">{technology}</span>)}</div></div></GlassPanel><GlassPanel><div className="relative"><div className="flex items-center gap-3"><GitBranch className="text-accent-primary" /><h2 className="font-display text-xl font-semibold">Scan event stream</h2></div><div className="mt-5 space-y-3 font-mono text-xs text-ink-muted">{["repository.imported", "repository.scanned", "dependency.graph_built", "knowledge_graph.built"].map((event) => <p key={event}><span className="text-status-success">●</span> {event}</p>)}</div></div></GlassPanel></section></main></div></div>;
}
