-- Manual Supabase SQL Editor deployment. Do not apply automatically.
-- Canonical MigrateOS planning schema; all IDs and audit times are server-managed.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end $$;

create table if not exists public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null check (char_length(name) between 1 and 120), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.repositories (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, provider text not null check (provider in ('github','local')), external_id text not null, default_branch text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id, provider, external_id));
create table if not exists public.repository_snapshots (id uuid primary key default gen_random_uuid(), repository_id uuid not null references public.repositories(id) on delete cascade, commit_sha text, branch text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(repository_id, commit_sha));
create table if not exists public.migration_plans (id uuid primary key default gen_random_uuid(), snapshot_id uuid not null references public.repository_snapshots(id), status text not null check (status in ('draft','awaiting_approval','approved','rejected','superseded')), version integer not null check (version > 0), summary jsonb not null, risk_score integer not null check (risk_score between 0 and 100), created_by uuid references auth.users(id), approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(snapshot_id, version));
create table if not exists public.migration_steps (id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.migration_plans(id) on delete cascade, step_key text not null, payload jsonb not null, priority integer not null check (priority between 1 and 5), risk text not null check (risk in ('low','medium','high','critical')), required_approval boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plan_id, step_key));
create table if not exists public.migration_reports (id uuid primary key default gen_random_uuid(), plan_id uuid not null unique references public.migration_plans(id) on delete cascade, report jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.agent_logs (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, event_type text not null, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.analysis_cache (id uuid primary key default gen_random_uuid(), snapshot_id uuid not null references public.repository_snapshots(id) on delete cascade, cache_key text not null, payload jsonb not null, expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(snapshot_id, cache_key));
create table if not exists public.events (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, sequence bigint not null, event_type text not null, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id, sequence));
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, actor_id uuid references auth.users(id), action text not null, resource_type text not null, resource_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.prompt_templates (id uuid primary key default gen_random_uuid(), name text not null, version integer not null check(version > 0), template text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(name, version));
create table if not exists public.execution_sessions (id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.migration_plans(id), status text not null check(status in ('queued','running','completed','failed','rolled_back')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists repositories_project_idx on public.repositories(project_id); create index if not exists snapshots_repository_idx on public.repository_snapshots(repository_id); create index if not exists plans_snapshot_status_idx on public.migration_plans(snapshot_id,status); create index if not exists steps_plan_priority_idx on public.migration_steps(plan_id,priority); create index if not exists events_project_sequence_idx on public.events(project_id,sequence); create index if not exists audit_project_created_idx on public.audit_logs(project_id,created_at desc);
create or replace view public.project_plan_overview with (security_invoker = true) as select p.id project_id, mp.id plan_id, mp.status, mp.risk_score, mp.created_at from public.projects p join public.repositories r on r.project_id=p.id join public.repository_snapshots s on s.repository_id=r.id join public.migration_plans mp on mp.snapshot_id=s.id;
do $$ declare tbl text; begin foreach tbl in array array['projects','repositories','repository_snapshots','migration_plans','migration_steps','migration_reports','agent_logs','analysis_cache','events','audit_logs','prompt_templates','execution_sessions'] loop execute format('alter table public.%I enable row level security',tbl); execute format('drop trigger if exists %I_updated_at on public.%I',tbl,tbl); execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',tbl,tbl); end loop; end $$;
