-- Manual Supabase SQL Editor deployment. Policies use project ownership via auth.uid().
create or replace function public.owns_project(target_project_id uuid) returns boolean language sql stable security invoker set search_path = public as $$ select exists(select 1 from public.projects where id=target_project_id and owner_id=(select auth.uid())) $$;
create policy "project owners manage projects" on public.projects to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy "owners manage repositories" on public.repositories to authenticated using (public.owns_project(project_id)) with check (public.owns_project(project_id));
create policy "owners read snapshots" on public.repository_snapshots for select to authenticated using (exists(select 1 from public.repositories r where r.id=repository_id and public.owns_project(r.project_id)));
create policy "owners manage plans" on public.migration_plans to authenticated using (exists(select 1 from public.repository_snapshots s join public.repositories r on r.id=s.repository_id where s.id=snapshot_id and public.owns_project(r.project_id))) with check (exists(select 1 from public.repository_snapshots s join public.repositories r on r.id=s.repository_id where s.id=snapshot_id and public.owns_project(r.project_id)));
create policy "owners manage steps" on public.migration_steps to authenticated using (exists(select 1 from public.migration_plans p join public.repository_snapshots s on s.id=p.snapshot_id join public.repositories r on r.id=s.repository_id where p.id=plan_id and public.owns_project(r.project_id))) with check (exists(select 1 from public.migration_plans p join public.repository_snapshots s on s.id=p.snapshot_id join public.repositories r on r.id=s.repository_id where p.id=plan_id and public.owns_project(r.project_id)));
create policy "owners read reports" on public.migration_reports for select to authenticated using (exists(select 1 from public.migration_steps st join public.migration_plans p on p.id=st.plan_id join public.repository_snapshots s on s.id=p.snapshot_id join public.repositories r on r.id=s.repository_id where p.id=plan_id and public.owns_project(r.project_id)));
create policy "owners manage project events" on public.agent_logs to authenticated using (public.owns_project(project_id)) with check (public.owns_project(project_id));
create policy "owners manage cache" on public.analysis_cache to authenticated using (exists(select 1 from public.repository_snapshots s join public.repositories r on r.id=s.repository_id where s.id=snapshot_id and public.owns_project(r.project_id))) with check (exists(select 1 from public.repository_snapshots s join public.repositories r on r.id=s.repository_id where s.id=snapshot_id and public.owns_project(r.project_id)));
create policy "owners manage events" on public.events to authenticated using (public.owns_project(project_id)) with check (public.owns_project(project_id));
create policy "owners read audit" on public.audit_logs for select to authenticated using (public.owns_project(project_id));
create policy "authenticated read prompts" on public.prompt_templates for select to authenticated using (active=true);
create policy "owners read sessions" on public.execution_sessions for select to authenticated using (exists(select 1 from public.migration_plans p join public.repository_snapshots s on s.id=p.snapshot_id join public.repositories r on r.id=s.repository_id where p.id=plan_id and public.owns_project(r.project_id)));
